### PR TITLE
Add rbx-3 to the build matrix

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by e2** [comment]
There's really no point in running RBX-2 and 3 at the same time. 3 is enough, even if it's broken.

**Comment by thedrow** [comment]
Got it.

**Comment by junaruga** [comment]
@rymai next PR to be merged could be this.
`rbx-2` has not been available environment on Travis any more. 
Current master branch
https://travis-ci.org/guard/listen/builds/387076637

**Comment by rymai** [comment]
@thedrow @junaruga Thanks! Superseded by https://github.com/guard/listen/pull/446.

**Pull request closed without merging**
